services:
    Shopping\ApiTKDeprecationBundle\EventListener\DeprecationListener:
        public: false
        arguments:
            - '@annotations.reader'
            - '@Shopping\ApiTKHeaderBundle\Service\HeaderInformation'
        tags:
            - { name: kernel.event_listener, event: kernel.controller }

    Shopping\ApiTKDeprecationBundle\Describer\AnnotationDescriber:
        public: false
        arguments:
            - '@nelmio_api_doc.routes.default'
            - '@Shopping\ApiTKCommonBundle\Util\ControllerReflector'
            - '@annotations.reader'
        tags:
            - { name: 'nelmio_api_doc.route_describer', priority: -2000 }